_target_: conglude.datamodule.ConGLUDeDataset

dataset_dir: ./data/datasets/train_datasets/pdbbind
dataset_name: pdbbind_val
task: train
structure_based: true
split: val
batch_size: 32

extract_ligands: from_file
labeled_smiles: none
calc_mol_feats: true
multi_ligand: false

debug: false
